spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(Yh4NfpYX/m/CUIjlvCp4jWYZJSWIonC+Zz7353CsUMtY7g+IG+ChwkHaOrN0eezLM4rYTzC0x57tNa++ucZdIYuqdLpa3oksWUZCLcAOX+si8BxDU3p17A==)
            client-secret: ENC(RtH+i0aunIgmy12FXe61+CObZpfdCNCoJy7k9FJRozUg+EhLySkn+dnbpaG7y+ZY)
            scope:
              - email
              - profile

          naver:
            client-id: ENC(03GvMWqjzIfA9jTFSGYrrh6I0i2OmGiY7ZSgvJdEie8=)
            client-secret: ENC(YzSFMwkd5/erH1aRV8uKT0uKBCLNh44G)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: email, nickname
            client-name: Naver

      # Provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response