spring:
  datasource:
    driver-class-name: ENC(TjtpzkBS6yzE2lu0ZemgIzsK4AUYN+z4Axqrz2kG4IQ=)
    url: ENC(JdPupoq7iChkoTVDTp/uFddPAkNCbDAewZdAGCvX/XkujI6fe8emrtvJoD9fSlIcwBBIAcjzfBI=)
    username: ENC(CaHyJFIih0mrolZnNi8WbA==)
    password: ENC(+rpSB9ezo2SMZJbhTBNfwA==)

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

  ### Spring Session
  session:
    store-type: jdbc
